import { useState } from "react";
import Link from "next/link";
import Head from "next/head";
import Footer from "@/Components/footer";
import Navbar from "@/Components/navbar";

export default function Home() {
  const [userInput, setUserInput] = useState("missingLink");

  const handleSubmit = () => {
    const input = userInput.trim();
    if (input === "" || input === "missingLink" || input === undefined) {
      return;
    }
    window.location.href = `/game/${input}`;
  };

  return (
    <>
      <Head>
        <title>fightingTime</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <h1 className="text-6xl font-bold text-center">
          Welcome to fighting-time
        </h1>
        <div className="flex flex-col items-center mt-10">
          <label htmlFor="gameNumber" className="text-2xl mt-2"> 
            Enter Game Number
          </label>
          <input
            id="gameNumber"
            type="text"
            className="border-2 border-black rounded-md p-2 mt-2"
            onChange={(e) => setUserInput(e.target.value)}
          />
          <button className="btn btn-primary mt-3" onClick={handleSubmit}> Submit </button>
        </div>
      </main>
      <Footer />
    </>
  );
}
